python numenta_encoder.py dataset/track01.csv encoding/track01_numenta.p
python numenta_encoder.py dataset/track02.csv encoding/track02_numenta.p
python numenta_encoder.py dataset/track03.csv encoding/track03_numenta.p
python numenta_encoder.py dataset/track04.csv encoding/track04_numenta.p
python numenta_encoder.py dataset/track05.csv encoding/track05_numenta.p
python numenta_encoder.py dataset/track06.csv encoding/track06_numenta.p
python numenta_encoder.py dataset/track07.csv encoding/track07_numenta.p
python numenta_encoder.py dataset/track08.csv encoding/track08_numenta.p
python numenta_encoder.py dataset/track09.csv encoding/track09_numenta.p
python numenta_encoder.py dataset/track10.csv encoding/track10_numenta.p